name: Test

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Aliyun CLI credentials
      uses: ./
      with:
        access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        region: ${{ env.ALIYUN_REGION }}

    - name: Upload a file to Aliyun OSS
      run: aliyun oss cp sample.html ${{ env.BUCKET_DESTINATION }} -r --acl public-read
      working-directory: ${{ env.WORKING_DIRECTORY }}

